// Пресет: Великий тест
window.DataManager.TEST_DATA_PRESETS.large = {
    label: '🏟️ Великий тест',
    description: '25 учасників, 8 різних призів',
    participants: [
        { name: 'Андрієнко Роман',     position: 'Спеціаліст', division: 'Відділ 1', weight: 1 },
        { name: 'Бойченко Ірина',      position: 'Аналітик',   division: 'Відділ 2', weight: 1 },
        { name: 'Василенко Павло',     position: 'Тімлід',     division: 'Відділ 1', weight: 2 },
        { name: 'Гончаренко Ольга',    position: 'Спеціаліст', division: 'Відділ 3', weight: 1 },
        { name: 'Даниленко Федір',     position: 'Менеджер',   division: 'Відділ 2', weight: 1 },
        { name: 'Євтушенко Ганна',     position: 'Спеціаліст', division: 'Відділ 4', weight: 1 },
        { name: 'Єрьоменко Тарас',     position: 'Тімлід',     division: 'Відділ 1', weight: 2 },
        { name: 'Жайворон Людмила',    position: 'Спеціаліст', division: 'Відділ 3', weight: 1 },
        { name: 'Захаренко Михайло',   position: 'Аналітик',   division: 'Відділ 2', weight: 1 },
        { name: 'Іванченко Лариса',    position: 'Менеджер',   division: 'Відділ 4', weight: 1 },
        { name: 'Карпенко Василь',     position: 'Спеціаліст', division: 'Відділ 1', weight: 1 },
        { name: 'Коваленко Зінаїда',   position: 'Тімлід',     division: 'Відділ 3', weight: 2 },
        { name: 'Лисиця Олег',         position: 'Спеціаліст', division: 'Відділ 2', weight: 1 },
        { name: 'Мазуренко Дарина',    position: 'Аналітик',   division: 'Відділ 4', weight: 1 },
        { name: 'Науменко Богдан',     position: 'Спеціаліст', division: 'Відділ 1', weight: 1 },
        { name: 'Олексієнко Тамара',   position: 'Менеджер',   division: 'Відділ 3', weight: 1 },
        { name: 'Павленко Анатолій',   position: 'Тімлід',     division: 'Відділ 2', weight: 2 },
        { name: 'Різниченко Катерина', position: 'Спеціаліст', division: 'Відділ 4', weight: 1 },
        { name: 'Семененко Юрій',      position: 'Аналітик',   division: 'Відділ 1', weight: 1 },
        { name: 'Тимченко Валентина',  position: 'Спеціаліст', division: 'Відділ 3', weight: 1 },
        { name: 'Удовиченко Степан',   position: 'Менеджер',   division: 'Відділ 2', weight: 1 },
        { name: 'Харченко Надія',      position: 'Тімлід',     division: 'Відділ 4', weight: 2 },
        { name: 'Цушко Антон',         position: 'Спеціаліст', division: 'Відділ 1', weight: 1 },
        { name: 'Шаповаленко Вера',    position: 'Аналітик',   division: 'Відділ 3', weight: 1 },
        { name: 'Щербаченко Іван',     position: 'Спеціаліст', division: 'Відділ 2', weight: 1 },
    ],
    prizes: [
        { name: '🏆 Гран-прі',                    count: 1 },
        { name: '💰 Грошовий сертифікат 500₴',    count: 2 },
        { name: '🎭 Квитки в театр',              count: 3 },
        { name: '🍕 Сертифікат в ресторан',       count: 3 },
        { name: '📱 Чохол для смартфону',         count: 4 },
        { name: '☕ Кавовий набір',               count: 4 },
        { name: '🧁 Торт на замовлення',          count: 2 },
        { name: '🎮 Ігрова картка 300₴',          count: 3 },
    ]
};
